
hrd:
  base-url: https://www.work24.go.kr/cm/openApi/call/hr/callOpenApiSvcInfo310L01.do
  detail-url: https://www.work24.go.kr/cm/openApi/call/hr/callOpenApiSvcInfo310D01.do
  keys:
    # ????????
    card: 7ec31f6c-6456-4b16-ae82-6d802051bdd5
    # ?????
    apprentice: f39accaa-be41-4c63-b5f1-9aea59af47a2

spring:
  datasource:
    url: jdbc:mysql://database-2.cxaicagyu6ru.ap-northeast-2.rds.amazonaws.com:3306/bytecookie?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: dev_user_ho       # ???? ??
    password: StrongPass!23
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # ????: create / update / validate ?? ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true
