hrd:
  base-url: https://www.work24.go.kr/cm/openApi/call/hr/callOpenApiSvcInfo310L01.do
  detail-url: https://www.work24.go.kr/cm/openApi/call/hr/callOpenApiSvcInfo310D01.do
  keys:
    card: ${KEY_CARD}
    apprentice: ${KEY_APPRENTICE}

recruit:
  api:
    key: ${RECRUIT_API_KEY}

openai:
  api-key: ${OPENAI_API_KEY}


spring:
  datasource:
    url: jdbc:mysql://database-2.cxaicagyu6ru.ap-northeast-2.rds.amazonaws.com:3306/bytecookie?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: dev_user_ho
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


springdoc:
  swagger-ui:
    display-request-duration: true
  api-docs:
    enabled: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  server-url: https://api-bytecookie.click

